grid_variant = 2

[factors]
x = [1, 2, 3, 4, 5, 6, 8, 9]
y = [1, 2, 3, 4, 5, 6, 8, 9]

[origins]
x = true
y = true

[regression]
print_linear_regression = true
draw_curve_of_best_fit = true
draw_error_curve_low_slope = false
draw_error_curve_high_slope = false
