grid_variant = 2

[factors]
x = [1, 1.5, 2, 3, 4, 5, 6, 8, 9]
y = [1, 1.5, 2, 3, 4, 5, 6, 8, 9]
offset_exponent_x = 2
offset_exponent_y = 1

[origins]
x = false
y = false

[linear_regression]
print_parameters = false
draw_curve_of_best_fit = false
draw_error_curve_low_slope = false
draw_error_curve_high_slope = false
