[paper]
file = 'grids/grid2.pdf'
width = 5846
height = 4133

[grid]
width = 5318
height = 3543
x = 264
y = 406
num_x_blocks = 27
num_x_tiny_blocks_per_block = 10
num_y_blocks = 18
num_y_tiny_blocks_per_block = 10

[drawing]
cross_size = 10
axis_tick_size = 20
