[paper]
file = 'grids/grid1.pdf'
width = 4133
height = 5846

[grid]
width = 3543
height = 5318
x = 406
y = 264

[x_axis]
type = "linear"
num_blocks = 18
num_tiny_blocks_per_block = 10

[y_axis]
type = "linear"
num_blocks = 27
num_tiny_blocks_per_block = 10

[drawing]
cross_size = 10
axis_tick_size = 20
