[paper]
file = 'grids/grid2.pdf'
width = 5846
height = 4133

[grid]
width = 5318
height = 3543
x = 264
y = 406

[x_axis]
type = "linear"
num_blocks = 27
num_tiny_blocks_per_block = 10

[y_axis]
type = "linear"
num_blocks = 18
num_tiny_blocks_per_block = 10

[drawing]
cross_size = 10
axis_tick_size = 20