[paper]
file = 'grids/grid2.pdf'
width = 5846
height = 4133

[grid]
file = 'input/grid1.pdf'
width = 5318
height = 3543
x = 264
y = 406
num_x_blocks = 270
num_x_blocks_per_super_block = 10
num_y_blocks = 180
num_y_blocks_per_super_block = 10

[drawing]
cross_size = 10
axis_tick_size = 20
